### ISSUE TITLE
js can not found error

### ISSUE THREAD

**Issue by OrangeSAM** [tsejx/javascript-guidebook#7]
访问各知识点的具体页面时，[比如](https://tsejx.github.io/javascript-guidebook/object-oriented-programming/object-understand/the-descriptor-methods)这个。 会遇到JS文件找不到导致404错误问题。

猜测是因为你从VuePress迁移到dumi导致的，我之前使用VuePress时也遇到了这个问题。

**Comment by tsejx** [comment]
已经修复了，感谢感喟🙏
